### ISSUE TITLE
The script doesn't work on not-fully-used store pages

### ISSUE THREAD

**Issue by Patrikperoz** [Tr345ure/xplay-store-enhance#1]
While playing with the xplay store filters a bit, I found a strange bug of both script-added buttons not appearing* below skin icons if specific combinations of filters are chosen, for example _"Store" + "Factory New"_ or _"Store" + "Well-Worn"_.

After summing up these results and the "inconsistence" of working and non-working combinations, i found an association: **the script won't work if the actual page isn't full** (contains 24 items). This theory seems to be correct, as there are same results for the last non-full pages with any filter combinaiton, and also, it is not the "last page issue", as the script works for them when they are full.

Still, the data about any item can be accessed by inverting the sorting by price, so this is not an emergency :P

While testing, no other extensions or scripts were in use. Hope this report helps you with the development of your cool store feature :)

* "_not appearing_" means not being loaded after at least one minute of waiting

**Comment by Tr345ure** [comment]
Hey, thank you for your detailed bug report. I will push a fix today or tomorrow.

**Comment by Tr345ure** [comment]
I have just pushed the fix for this: eb2e0cc2c8c3881320456f8723442495fdb31913
Thanks again for creating this issue. :)
