### ISSUE TITLE
@match with active Type filter in the store

### ISSUE THREAD

**Issue by Maikerru** [Tr345ure/xplay-store-enhance#3]
When a Type is selected in the store (for example with only Pistol Type selected the url changes to https://xplay.gg/store/pistols) the url can change and after a refresh the extension is not loaded
![msedge_xDIz93WWpL](https://github.com/Tr345ure/xplay-store-enhance/assets/24543438/7daa0b5e-6d56-4667-9514-a2b037430b87)

**Comment by Tr345ure** [comment]
Hey, thanks for making me aware of this. The store URLs are all over the place after the language update... Just pushed a fix for this: a104906665719ac3f2e5d7c6c90994a0d5bad58c
